### ISSUE TITLE
Stability Improvement Progress Tracking

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/obs-StreamFX#109]
StreamFX is currently riddled with leaks, crashes, double releases and other issues. 

### ToDo
- [x] 3D Transform Filter
- [x] Blur Filter
- [x] Color Grade Filter
- [x] Dynamic Mask Filter
- [x] SDF Effects Filter
- [x] Source Mirror Source
