### ISSUE TITLE
Nvidia Face Tracking: Add dynamic downscaling to deal with GPU intensive games

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/obs-StreamFX#150]
## Description
When playing games that are really GPU intensive or also using Tensor resources, the Nvidia Face Tracking filter starts taking 300+ms. Therefore we should reduce the resolution until updates are real time again, and undo that when they are faster than real time.

This should happen silently, and ideally should not affect tracking at all. The user should not be affected by the dynamic downscaling, other than maybe getting a slightly larger tracking region.

### Checklist:
- [x] I have read the contribution guidelines.
- [x] This feature is necessary and can't be done through other means.
- [x] This feature does not break existing functionality.
- [x] I am willing to hire/pay someone to implement this.

**Comment by Xaymar** [comment]
Initialization has been moved to an extra thread now, which should drastically reduce load times below what they were until now.

**Comment by Xaymar** [comment]
Discovered that NvAR_Run must run synchronously with Direct3D11, which effectively removes the usefulness of threading at least for that task. Hoping that the SDK support can help with solving this issue.

**Comment by Xaymar** [comment]
The recent improvements have made the majority of the filter run asynchronously, which drastically improved rendering while not actually taking away too much libOBS render time at all. There is still a lot to investigate, including how to make NvAR_Run fully asynchronous.

**Comment by Xaymar** [comment]
According to information from Nvidia, this is already done internally. However this seems to be done _after_ the conversion to BGR24, so maybe some benefit can be gained by downscaling first.

Anyway, in all measurements, the RGBA to BGR24 conversion took around 1.5ms. The remaining ~3.3ms were taken up by NvAR_Run

**Comment by Xaymar** [comment]
Debugging revealed that the internal resolution seems to be 256x256 or 128x128, so dynamic downscaling wouldn't be useful. Instead static downscaling to that size might improve things.

**Comment by Xaymar** [comment]
With the announcement of the NVIDIA Broadcast app, integration of the SDK will be deprecated and discontinued.
